### ISSUE TITLE
Transfer file formats

### ISSUE THREAD

**Issue by Hermann12** [marp-team/marp-cli#129]
Why not insert this in Pandoc? Is the target combine the CLI into Marp later?

**Comment by yhatt** [comment]
Marp CLI focuses on producing same view in some formats converted from a single Marp Markdown. On the other hand, Pandoc focuses the interconversion between many formats by using intermediate representation. 

Even if Pandoc could convert Markdown into Marp, I guess the all of features of Marp (e.g. Directives, image syntax, and so on...) could not use because it will be lost a lot of expressive features while conversion.

See also: https://pandoc.org/MANUAL.html#description

> Because pandoc’s intermediate representation of a document is less expressive than many of the formats it converts between, one should not expect perfect conversions between every format and every other. Pandoc attempts to preserve the structural elements of a document, but not formatting details such as margin size. And some document elements, such as complex tables, may not fit into pandoc’s simple document model. While conversions from pandoc’s Markdown to all formats aspire to be perfect, conversions from formats more expressive than pandoc’s Markdown can be expected to be lossy.
