### ISSUE TITLE
output html does not copy local assets

### ISSUE THREAD

**Issue by jingsam** [marp-team/marp-cli#159]
I use this command to convert a set of markdown files to html files:

```
marp --input-dir=./slides --output=./dist
```

However, local assets such as images and videos do not copy to `dist` directory. Is there possibility that `marp` could autodect referenced local assets and copy to `dist` directory？Just like what `webpack` do? Otherwise, I should manually copy that assets to dist.

**Comment by yhatt** [comment]
Marp CLI just aims to transform the file type from `.md` to any types. Assets won't handle in HTML conversion because we are not a bundler. We are nervous handling local file assets as you can see from [the recommendation to use assets uploaded to online](https://github.com/marp-team/marp-cli#security-about-local-files).

Perhaps you may bundle local assets by passing converted HTML into webpack through html-loader.

**Comment by yhatt** [comment]
In future, [Web Bundles](https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html) draft and [wbn](https://www.npmjs.com/package/wbn) may help to bundle local resources into one file.

**Comment by yhatt** [comment]
Close for housekeeping. Currently we are in favor of using [monolith](https://github.com/Y2Z/monolith) together with Marp: marp-team/marp#132
