### ISSUE TITLE
Cannot change serif font in pdf output and vscode preview

### ISSUE THREAD

**Issue by Dothion** [marp-team/marp-cli#161]
Serif Chinese font isn't a good choice in slides, so I tried this, but font didn't change.
```
---
marp: true
theme: gaia
---
<style>
.slide {
  font-family: 'Microsoft YaHei', 'SimHei', sans-serif !important;
}
</style>

<!-- class: lead gaia -->
# 标题
## Title
```
I didn't try it with html output because html version without `<style>` worked well with a sans serif font.
So is there any way to change font without editing theme files?

btw Microsoft YaHei might not be a good default font because it is not a free font. [Sarasa Gothic](https://github.com/be5invis/Sarasa-Gothic) may be a good alternative.
![screenshot](https://user-images.githubusercontent.com/31262977/65296309-9d2c1500-db96-11e9-9a20-ea2b5bfa843c.PNG)

**Comment by yhatt** [comment]
`.slide` selector is only for [outdated Marp app](https://github.com/yhatt/marp). Instead, Marp Next must use `section` selector. 

```html
<style>
section {
  font-family: 'Microsoft YaHei', 'SimHei', sans-serif;
}
</style>
```

See also the document of theme CSS in [Marpit framework](https://marpit.marp.app/theme-css).

Incidentally, [Gaia has already defined sans-serif font in theme CSS](https://github.com/marp-team/marp-core/blob/master/themes/gaia.scss#L218-L219) so I think rendering with serif font is unexpected behavior. I was going to consider CJK rendering well because I'm Japanese, but the result in Chinese fonts is intersting for me.

**Comment by Dothion** [comment]
It's working well. Thanks a lot.
