### ISSUE TITLE
Disable Fragmented list

### ISSUE THREAD

**Issue by nalmeida** [marp-team/marp-cli#188]
Is there an option / config to disable "Fragmented list" ?

**Comment by yhatt** [comment]
No, there isn't easy way to disable. In Marpit framework [we had thought about configurable fragmented list once](https://github.com/marp-team/marpit/pull/148) but we prioritized the less-configuration.

- Simply use `-` / `1.` instead of `*` / `1)` to avoid fragmented list.
- Marp CLI can customize engine via JavaScript. Try to use `--engine engine.js` option with this if you want to disable:

```javascript
// engine.js
// You have to run `npm i @marp-team/marp-core` at first.
const { Marp } = require('@marp-team/marp-core')

module.exports = opts => {
  const marp = new Marp(opts)

  // Disable parsing fragmented list
  marp.markdown.core.ruler.disable('marpit_fragment')

  return marp
}
```

Please feedback to [the issue tracker of Marpit framework](https://github.com/marp-team/marpit/issues) if you think that is better to provide a way for disabling fragmented list via such as directive.

**Comment by nalmeida** [comment]
Used the ```-``` and ```1.``` notation.
