### ISSUE TITLE
Animated gifs aren't being exported to pptx

### ISSUE THREAD

**Issue by asm0dey** [marp-team/marp-cli#196]
When I'm adding animated gif to my presentation like this:

```markdown
---
<!--
_class:
-->

<style scoped>
section img{
    position: absolute;
    right: 0;
    bottom: 0;
}
</style>

![bg left:30% fit](images/VM.png)

# Django

- А где логика?

![](images/7VE.gif)
```

They are being displayed correctly in html, but not in PPTX/PDF, there they are just static images.

**Comment by yhatt** [comment]
Any kind of animations and interactives are lost in PPTX conversion because we are rendering each slide pages as static image.

If we supported these, have to work for reproducing HTML rendering in PPTX. Honestly it's like a re-invintention of browser, and not realistic within the scope of Marp project.

There is similar discussion in https://github.com/marp-team/marp-cli/issues/166#issuecomment-536827067.

**Comment by asm0dey** [comment]
TBH I've already discovered it while investigating structure of generated PPTX :)
Possibly there is a way to cut animated GIFs out of source and pasting them into slide at computed coordinates?

**Comment by yhatt** [comment]
If you don't mind hacking Marp CLI, you can detect images from rendered HTML by Chrome / Chromium through [Puppeteer](https://github.com/puppeteer/puppeteer), and add rendered animation GIF through [PptxGenJs `addImage()` method](https://gitbrent.github.io/PptxGenJS/docs/api-images.html).

Please remember a way to place image is not only `<img>`. Marp may take `<figure>` and style (`background-image`). Sometimes they also should consider visibility, `z-index`, overlapped text, filter, and a lot of expressive CSS.

...Yep, it's unrealistic for us. :p

**Comment by asm0dey** [comment]
OK, fair enough, I'll stick with HTML view :)
