### ISSUE TITLE
Fallback to Microsoft Edge if not installed Chrome

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-cli#199]
[Microsoft has started rolling out new Edge browser based on Chromium.](https://blogs.windows.com/msedgedev/2020/01/15/upgrading-new-microsoft-edge-79-chromium/) It will gradually be made available on Windows Update.

This fact is lucky for Marp CLI. PDF/PPTX conversion and preview mode has to install an extra Chrome/Chromium browser. Currently, it also works with Edge by setting `CHROME_PATH` environment variable.

It means the most of Windows 10 user will get the compatible browser without to do anything by user. If Marp CLI was supported fallback to Edge, installing extra browser won't be needed when converting Markdown into PDF/PPTX.

**Comment by ShGKme** [comment]
Isn't it a work of [chrome-launcher](https://github.com/GoogleChrome/chrome-launcher) package?

CLI just use it's path 
https://github.com/marp-team/marp-cli/blob/003fb6bb1ddfcd9e4636d5a114e5bb8ff276231b/src/utils/puppeteer.ts#L75

**Comment by yhatt** [comment]
@ShGKme chrome-launcher is only _designed for Google Chrome and Chromium_, not for Chromium-flavored browsers such as Edge.

**Comment by ShGKme** [comment]
@yhatt But if `CHROME_PATH` is set to `C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe`, it works fine.

If it's not work for `chrome-launcher`, then maybe it's possible to add check to `puppeteer.ts`, that process.platform === 'win32' and msedge exists on usual paths.

I may do a PR if this solution is ok.

**Comment by yhatt** [comment]
In short term the limited fallback to Edge in Windows would be no problem. However, eventually we have to use (or create) Chromium Edge finder for Windows, [macOS](https://www.microsoftedgeinsider.com/ja-jp/download?platform=macos), and [Linux](https://www.microsoftedgeinsider.com/download/?platform=linux) as same as [`chrome-finder.ts` in chrome-launcher](https://github.com/GoogleChrome/chrome-launcher/blob/master/src/chrome-finder.ts).

**Comment by ShGKme** [comment]
Edge is default only on Windows. 

I thought, the idea was that windows users should be able to use already installed Edge without any actions as it is. Just because it works and the browser is already installed.

If any user has a normally installed Chrome, it would be found by `chrome-launcher`.
If user only has something unusual (like Brave or Edge on Mac), then user must provide the path. Same if user has browser installed to non-usual place. 

Right now Edge has only 1 (ok, +1 more for Beta version) place to be installed by default in Windows (`%programfiles%\Microsoft\Edge\Application\msedge.exe`). 

Of course, another way is to use some 3rd package, which would found any chromium-based browser on any OS. And add cli arg for choose like in Cypress.

**Comment by yhatt** [comment]
Here is the one of reliable way to resolve the executable path of Edge, by Microsoft (microsoft/vscode-edge-devtools):
https://github.com/microsoft/vscode-edge-devtools/blob/5056752615b3f4332dc27242b008699075dcefce/src/utils.ts#L494-L524
