### ISSUE TITLE
Slides with code block always verbalized by screen-reader

### ISSUE THREAD

**Issue by ivanfetch** [marp-team/marp-cli#236]
I'm visually impaired and use the Apple Voiceover screen-reader. When looking HTML output, the screen-reader always verbalizes slides that contain a code-block, even though those slides are not shown visually.

For example, if I have 6 slides, and slides 3 and 5 contain a code-block, when I'm viewing slide 4, my screen-reader verbalizes slides 3, 4, and 5. Slides 3 and 5 are always heard, even when they are not shown.

Ideally the screen-reader only "sees" the current slide that is being visually displayed.

I've created a video to help demonstrate this in action: http://ivanfetch-media.s3.amazonaws.com/marp-codeblock-screenreader.mp4

Any idea what might be causing this, and what it may take to resolve? I'd really like to use Marp to present slides next week, but can't have extraneous slides being read to me.

Here is the markdown I used in the above video:
[test.md.txt](https://github.com/marp-team/marp-cli/files/4841077/test.md.txt)

I appreciate folks taking a look, and any ideas you may have!

**Comment by yhatt** [comment]
Thanks for your valuable feedback. For now, accessibility is hardly considered in the generated HTML by Marp CLI. We have to improve the experience for the screen reader as you pointed out.

### What happening in HTML?

Inactive slide pages look like hiding visually but actually hide behind the current page because they need to keep showing for preloading resources. Almost pages will get really hidden after loading resources (#143), and contents in them should not read out by screen reader.

However, pages that include code block won't hide to avoid bug reported in #153. Perhaps the screen reader is recognizing them.

### To improve

Marp CLI's `bespoke` template has to control [`aria-hidden` attribute](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute) for slide pages, to prevent reading out semantically hidden pages.

**Comment by yhatt** [comment]
@ivanfetch Fixed in [v0.18.2](https://github.com/marp-team/marp-cli/releases/tag/v0.18.2). Try using the latest Marp CLI release.

**Comment by ivanfetch** [comment]
Thank you @yhatt - this is a much better screen-reader experience using the HTML slides! I very much appreciate your help - please let me know if there may be anything I could do to return the favor.
