### ISSUE TITLE
Global Theme Installation

### ISSUE THREAD

**Issue by engineerjoe440** [marp-team/marp-cli#247]
Hello, I'm looking to start using MARP for some technical presentation generation for my team, and I want to be able to create a theme for my group that could be "installed globally" such that the theme could just be declared in the markdown and wouldn't need to be declared as an argument to the command line. Something like the following:

```
---
theme: my-company-theme
marp: true
---
```

I've been struggling to find if this is already supported, and if so, how it can be done. I've already globally installed MARP according to the README in the marp-cli repo: `npm install -g @marp-team/marp-cli` so that I can just call the appropriate command from any directory on my machine (which I think is what will work best for my team).

Is there already support for what I've described, or is this something of a new feature? Also, forgive me if I'm not opening this issue in the most appropriate repository, let me know if I can further describe my use case!

**Comment by yhatt** [comment]
Marp CLI requires [`--theme` or `--theme-set` option](https://github.com/marp-team/marp-cli#theme) explicitly whenever using external themes, because we think implicit theme loading may make some confusions and *potentially security risks*.

Installation with `-g` flag is [known as evil](https://medium.com/@drag13dev/npm-install-g-is-evil-b07c7e3325bf) and Marp team does not recommended too (but commonly used widely so documented just for convenience). If your team has to use team-specific theme, the recommended solution is using Marp CLI on the project that includes custom theme, instead of using global `marp` command.

**Comment by engineerjoe440** [comment]
Hi @yhatt ! Thank you for that info! I spend a lot of time developing in Python, and it sounds very familiar, though I definitely think that there is value in having a way to "*install*" themes so that they can be used like the built-in themes. At any rate, thank you so much for the response! This project is fantastic!!!!

**Comment by yhatt** [comment]
Thanks for your feedback! The installable Marp theme is interesting idea :smile:
