### ISSUE TITLE
Docker image: Upgrade Required

### ISSUE THREAD

**Issue by ricardo-reis-1970** [marp-team/marp-cli#280]
Hi all,

I started using Docker and Markdown years ago, and HTML/CSS/JS decades ago. I'm native.
I started trying Marp 15 minutes ago. Please be patient. I'm using the example from `https://marp.app/`, the 2 slides presentation.

I'm trying to use Marp's [Docker image](https://hub.docker.com/r/marpteam/marp-cli/) with Marp, before I start wondering how exactly should I put the whole environment together locally.

As per the Docker page, I am using the `docker run` commands and it works like a charm for conversions, **as soon as you figure out that in Windows 10, you need to use Docker Desktop to share folders with `docker`**. Both PDF, HTML and PPTX look like a million Euros covered in gold and sprikled with diamonds, and that alone is the final argument to immediately adopting Merp: Done! :satisfied:

However, the command
```
docker run --rm --init -v $PWD:/home/marp/app/ -e LANG=$LANG -p 37717:37717 marpteam/marp-cli -w slide-deck.md
```
with `$PWD` converted to double quoted absolute path and `$LANG` converted to `en_uk.UTF-8`, is resulting in an error message. The command line seems ok, outputting:
```
[  INFO ] Converting 1 markdown...
[  INFO ] slide-deck.md => slide-deck.html
[  INFO ] [Watch mode] Start watching...
```
but opening `http://localhost:37717/` results in the message `Upgrade Required`.

I literally just downloaded the image, reported as updated 8 days ago. I'm running `Docker version 19.03.12, build 48a66213fe`, the latest engine, from 2020-06-18.

What should I upgrade?

**Comment by yhatt** [comment]
Probably you are using a wrong mode. If you require slide hosting by HTTP, please use server mode (`-s`) instead of watch mode (`-w`). [In the example of server mode command in Docker Hub](https://hub.docker.com/r/marpteam/marp-cli/), you can serve slide deck with `http://localhost:8080/`.

Port 37717 is internally needed for watching the change of Markdown located in Windows through WebSocket protocol. But **this port does not assumed HTTP access by user**. ["426 Upgrade Required"](https://httpstatuses.com/426) means "Requires upgrade from HTTP protocol to WebSocket protocol". Usually the end-user cannot understand this meaning, and should rather not understand too.

**Comment by ricardo-reis-1970** [comment]
Hi Yuki,

Thank you for the quick reply, and no less for staying up so late to humour me.

I actually should apologise for not having updated my question sooner. I tried `-s` and *of course* it is working, from Docker and all. I'm writing several training courses and I'm definitely using `marp`.

I would like to help. I can't sponsor anyone, as I am unemployed, but I will be in touch with contributions.

Arigato!
Ricardo
