### ISSUE TITLE
Theme asset directory

### ISSUE THREAD

**Issue by phillebaba** [marp-team/marp-cli#291]
I have a repository that contains multiple decks and I want to share a theme between them. Using `--theme-set` works well with the caveat that I can't have assets for the theme, like fonts or background images.

My repository looks similar to the following.
├── presentations
│    |── presentation #1
│    |  ├── assets
│    |  └── slide-deck.md
│   └── presentation #2
│       ├── assets
│       └── slide-deck.md
└── themes
    ├── assets
    └── theme.scss

Only the assets in the presentation directory will be accessible, when running the server or generating the html. Is there a way to solve this?

**Comment by yhatt** [comment]
Using local file assets in theme CSS is not recommended because it cannot keep consistent resolution in every Marp environments.

All of Marp theme CSS should keep its portabillity by using online uploaded assets, or inline data URIs [as Marp Core does so in build process](https://github.com/marp-team/marp-core/blob/master/rollup.config.js#L44-L48). They are not depending on the location and usage of Markdown, and useful for preventing to make unintended security hole about local files in third-party themes.
