### ISSUE TITLE
Support terminal-based presenations

### ISSUE THREAD

**Issue by ceuk** [marp-team/marp-cli#297]
Hi,

It might be nice to be able to use something like [Glow](https://github.com/charmbracelet/glow) to render the slides in the actual terminal with simple prev/next/quit controls. 

If I get the time to submit a PR would this be a welcome feature do you think?

**Comment by yhatt** [comment]
That's an interesting idea but we may not take that due to sound like a little too niche.

Marp CLI should be a converter of just Marp / Marpit, HTML + CSS based slide. We want to hear what Marp community think about this idea.

If you are finding CLI-based presentation, I'm sure you'll like a tool such as https://github.com/visit1985/mdp and https://github.com/tslide/tslide. Especially the first one has amassed about 4k stars (twice of Marp).
