### ISSUE TITLE
Export to Native PowerPoint

### ISSUE THREAD

**Issue by yumoraby** [marp-team/marp-cli#298]
The current PowerPoint export, essentially exports each slide as a static image. Is there anyway to export to native PowerPoint? So that its is easier to redistribute?

Maybe export using openXml?

**Comment by yhatt** [comment]
> Transferred from Marp Core because PowerPoint export is essentially a feature of Marp CLI. 🚚 

Marp has focused on the visual reproducibility of HTML + CSS slides. So we think rendering static images is the best solution to export good looking PowerPoint from HTML-based slide.

Making a native PowerPoint with keeping reproducibility of HTML would be too hard to implement in Marp team because it's just like reinventing the rendering engine of the browser.

- Try PPTX conversion from the exported PDF by Marp, through Adobe Acrobat or some online PDF2PPTX service. Them visual reproducbillity are OK but they may use different fonts. See also: https://github.com/marp-team/marp-cli/issues/166#issuecomment-536827067
- Try using [Pandoc](https://pandoc.org/). It can convert Markdown presentation into the editable PPTX (Required a template PPTX if you want to change theme).

> |Current PPTX generation<br />(Not editable / Perfect reproducibility)|PDF -> PPTX by Adobe Acrobat<br />(Editable / Incorrect renderings)|
> |:---:|:---:|
> |![marp-pptx](https://user-images.githubusercontent.com/3993388/65928915-bb1d3380-e43a-11e9-8129-12c182240c46.png)|![adobe-acrobat](https://user-images.githubusercontent.com/3993388/65928937-cff9c700-e43a-11e9-8cb3-245edfa55ed4.png)|
> 
> -- _https://github.com/marp-team/marp-cli/issues/166#issuecomment-536827067_

**Comment by yumoraby** [comment]
> > Transferred from Marp Core because PowerPoint export is essentially a feature of Marp CLI. 🚚
> 
> Marp has focused on the visual reproducibility of HTML + CSS slides. So we think rendering static images is the best solution to export good looking PowerPoint from HTML-based slide.
> 
> Making a native PowerPoint with keeping reproducibility of HTML would be too hard to implement in Marp team because it's just like reinventing the rendering engine of the browser.
> 
> * Try PPTX conversion from the exported PDF by Marp, through Adobe Acrobat or some online PDF2PPTX service. Them visual reproducbillity are OK but they may use different fonts. See also: [#166 (comment)](https://github.com/marp-team/marp-cli/issues/166#issuecomment-536827067)
> * Try using [Pandoc](https://pandoc.org/). It can convert Markdown presentation into the editable PPTX (Required a template PPTX if you want to change theme).
> 
> > Current PPTX generation(Not editable / Perfect reproducibility)
> > PDF -> PPTX by Adobe Acrobat(Editable / Incorrect renderings)
> > 
> > 
> > 
> > 
> > ![marp-pptx](https://user-images.githubusercontent.com/3993388/65928915-bb1d3380-e43a-11e9-8129-12c182240c46.png)
> > ![adobe-acrobat](https://user-images.githubusercontent.com/3993388/65928937-cff9c700-e43a-11e9-8cb3-245edfa55ed4.png)
> > 
> > 
> > 
> > -- _[#166 (comment)](https://github.com/marp-team/marp-cli/issues/166#issuecomment-536827067)_

Thanks @yhatt  this helps a lot :)

**Comment by Foadsf** [comment]
has anyone tried [`marp2pptx`](https://github.com/ebibibi/marp2pptx)?

**Comment by yhatt** [comment]
@Foadsf It is made by Python that means that _it does not use Marp ecosystem_ (`@marp-team/marp-core` or `@marp-team/marpit`),  so it may not compatible as the output of usual Marp slide.

Marp CLI has already provided an experimental `--pptx-editable` option to export the native PowerPoint format (#626).
