### ISSUE TITLE
Output standalone HTML

### ISSUE THREAD

**Issue by wleoncio** [marp-team/marp-cli#302]
I often feel the need to generate standalone HTML files for my presentations. Currently, I just use [monolith](https://github.com/Y2Z/monolith) for that, simply invoking `monolith file.html -o fileStandalone.html` from a command line.

This is simple enough, but I wonder if there's any interest in adding such a feature to Marp CLI so users don't have to look for extra software for this useful feature which makes an HTML file as portable and universal as a PDF while also being better suited for screen display.

**Comment by yhatt** [comment]
Marp CLI is not a bundler as mentioned in #159. If that could done with monolith, we would not do the same because we think CLI tool should follow [the UNIX philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Mike_Gancarz:_The_UNIX_Philosophy): _Small is beautiful, Make each program do one thing well, and so on._

If monolith accepted stdin input, `echo your-slide.md | marp | monolith -o ./output.html` as one liner may work.

**Comment by wleoncio** [comment]
Fair enough, hard to argue as a preacher of the UNIX philosophy myself. :)
