### ISSUE TITLE
Failed converting markdown while trying with other extension file than default (html)

### ISSUE THREAD

**Issue by b3j0f** [marp-team/marp-cli#316]
Hello,

I meet this error when I try to convert my md with other file format than html (test with pdf, pptx and image) :

[ ERROR ] Failed converting Markdown. (Cannot read property 'toString' of null)

My environment is debian over wsl2.

What could I do to fix that ?

**Comment by yhatt** [comment]
First, Marp needs to install Google Chrome / Chromium or Microsoft Edge prior to converting slide deck into PDF, PPTX, and image.

Marp CLI tries to use Chrome in Windows for conversion in WSL, but _it's available only in WSL1_ due to the difference of network architecture.

WSL2 should install Chrome or Chromium to your Linux distribution, and specify the binary path through `CHROME_PATH` env: `CHROME_PATH=/usr/bin/chromium-browser marp example.md --pdf`. See also https://github.com/marp-team/marp-cli/issues/288.

**Comment by b3j0f** [comment]
Sorry, I just saw this note in the README.

It works perfectly, thanks !
