### ISSUE TITLE
How to deactivate action of (mouse) scroll wheel (go to next slide)?

### ISSUE THREAD

**Issue by sbibauw** [marp-team/marp-cli#340]
I love Marp, but when I'm presenting, using an Apple Mouse, the scroll wheel gets very often moved without my intent and then it makes the slideshow move to the next/previous slide(s)/event(s) very fast.

1. Is it possible to deactivate this action of the mouse scroll wheel?
2. I think it would be better deactivated by default (most of us expect using either the Space bar or the [→] key to go to the next slide, not the scroll wheel).

**Comment by yhatt** [comment]
Transferred from Marp Core :arrow_forward: Marp CLI :truck:. Wheel navigation is a part of Marp CLI's template `bespoke`.

1. No. Always works for now.
2. It's discussable in this issue or [our community](https://github.com/marp-team/marp/discussions). But I don't think so. IMO I don't really want to disable it by default:
      - Wheel navigation is familiar control in many presentation tools such as PowerPoint and Google Slide.
      - For the most of visitors to public HTML presentation, wheel control feels like a primary control for web.
      - I believe it can resolve by adjusting sensitivity of wheel event. (following)

I don't have Magic Mouse so can't test actual behavior, but all of swipe gestures should fire events as by mouse wheel because JavaScript cannot detect what kind of device for navigation.

Marp CLI's bespoke template has already included a special handling for mouse wheel event(s): [A basic handling to prevent continuous events by momentum scroll](https://github.com/marp-team/marp-cli/blob/fce51018b2a6573fd4e75e7755db7590ad1ce238/src/templates/bespoke/navigation.ts#L58-L69) (triggered by Magic Trackpad and also maybe Magic Mouse). But not yet handled ​high sensitivity against the fine movement of the finger on Magic Mouse.

I think we can get both of responsive and not too sensitive navigation by tuning wheel events in some approaches: Setting delta threshold for starting navigation, and throttling continously brought wheel events.

We want to hear more feedbacks from Magic Mouse user.

**Comment by sbibauw** [comment]
Thanks @yhatt. OK, maybe indeed a reduction in sensitivity adapted to the Magic Mouse could be an option. Right now, I really have a problem that my slides often go 3-4 steps backward without any intent.

If not, then the possibility (if easy to implement) to deactivate this in the configuration of Marp-CLI/Marp-vscode would work for me as well.

**Comment by yhatt** [comment]
Personally I have interested how other Web-based presentation tools such as Google Slides are resolving Magic Mouse problem. If navigation worked comfortable in them, Marp should be better to apply improvement in similar way too.

In the meantime, you can use this workaround:

1. Open DevTools in your browser (Hit <kbd>F12</kbd> in the case of most browsers)
2. Input following to console, and <kbd>Enter</kbd>.<br /><br />
    ```javascript
    document.addEventListener('mousewheel', e => e.stopPropagation(), true)
    ```

Now any wheel events have prevented.

**Comment by yhatt** [comment]
Marp CLI v1.1.0 has released with tuned wheel sensitivity against Multi-touch devices like the trackpad and Magic Mouse. I hope it is reduced too sensitive navigations with Apple Mouse.

Even if not satisfied with the updated behavior, the workaround in above will work continously.

> By this change, the navigation experience by the other device may be degraded. We are welcome to various feedbacks continuously from users using a particular device!
