### ISSUE TITLE
PlantUML diagrams show CSS / HTML code instead of images

### ISSUE THREAD

**Issue by timoguic** [marp-team/marp-cli#397]
### Version of Marp Tool

@marp-team/marp-cli v1.4.1 (w/ customized engine)

### Operating System

Windows

### Environment

- OS version: Windows 10
- Node.js version: v12.16.1

Tested on Linux Ubuntu 18.04 and 20.04 and with NodeJS v14.16.0 too.

### How to reproduce

1. Install marp-cli
2. Install markdown-it-plantuml
3. Create custom [`marp.config.js`](https://github.com/marp-team/marp-cli#configuration-file):
```javascript
const markdownItContainer = require('markdown-it-plantuml')

module.exports = {
  // Customize engine on configuration file directly
  engine: ({ marp }) => marp.use(markdownItContainer, 'custom'),
}
```
4. Create MD document and convert it
5. 
![image](https://user-images.githubusercontent.com/637649/139621458-b60d668e-e11c-421a-bad1-a52c1cbc0666.png)
6. Same problem when converting to HTML format

### Expected behavior

The PlantUML diagrams show up as images

### Actual behavior

The PlantUML diagrams show up as code (CSS?)

**Comment by yhatt** [comment]
We could not reproduce. markdown-it-plantuml seems working correctly in a simple case:

![test](https://user-images.githubusercontent.com/3993388/139632307-64d359e9-3a36-46fb-b742-451bfd7d45a2.png)

(Tested in `gaia` theme. In other themes, the diagram will be stretched unnecessarily because of markdown-it-plantuml will put an inline image without any block containers such as `<p>` element. This is not a bug of Marp, and you can be dealt with by [setting custom `render` function in the option of markdown-it-plantuml](https://github.com/gmunguia/markdown-it-plantuml#advanced-usage).)

Could you share a reproducible Markdown?

**Comment by timoguic** [comment]
This is the Markdown I am using:
```
# Header

```plantuml
@startuml

class Example {
    + attribute
    - method()
}

@enduml
```

---

# Next slide
```

**Comment by yhatt** [comment]
Still failure to reproduce. [markdown-it-plantuml](https://github.com/gmunguia/markdown-it-plantuml) does not recognize `@startuml` and `@enduml` within the code block, so the output that is converted from your reproducible Markdown should not have any diagrams. (See also: https://github.com/gmunguia/markdown-it-plantuml/issues/11)

![](https://user-images.githubusercontent.com/3993388/139835705-9c60eb8d-28e7-4f05-ae41-3d22b2f4e91b.png)

[Are not you actually using a different library for rendering plantuml?](https://www.npmjs.com/search?ranking=popularity&q=keywords%3Amarkdown-it-plugin%20plantuml)

**Comment by yhatt** [comment]
Close for housekeeping.
