### ISSUE TITLE
theme-set usage?

### ISSUE THREAD

**Issue by jhconning** [marp-team/marp-cli#440]
I am able to get a custom theme working using the vs-code extension but I am not able to get it to work from the command line. 

Consider the marp themes shared by another user at: https://github.com/cunhapaulo/marpstyle 
I've cloned that repo to my window machine and place myself at the root of the folder structure that includes a structure and files like this:

```
\ 
   \examples
      example-kant.md
   \style
      kant.css
```
and I then issue this command pointing to the ./style folder (which contains 3 .css files needed: kant.css, ):

`marp --server ./examples --theme-set ./style`

This invokes the server but when I click on `example-kant.md` the slide presenter rendered version looks like this:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/5048607/161401512-a2e9333d-36ef-4a7c-a286-cdc051986087.png">

Whereas the same deck using the vscode extension looks like this: 
<img width="367" alt="image" src="https://user-images.githubusercontent.com/5048607/161402944-1b9a2f26-80ed-4600-ac7a-0762f0957116.png">

Any clues as to what I might be doing wrong?  

And a related question,  could I have the theme-set option point to an URL (say the github folder with the styles https://github.com/cunhapaulo/marpstyle/tree/main/style)?

**Comment by yhatt** [comment]
It looks like no problems about loading custom theme in Marp CLI. I've tried the same command too but the custom theme was applied to the slide correctly.

If the custom theme that you are using is depending on raw HTML, add [`--html` option](https://github.com/marp-team/marp-cli#:~:text=Enable%20or%20disable%20HTML%20tags) to enable HTML tags in Markdown. As same as VS Code extension, Marp CLI does not render raw HTML tags by default due to security reason.

Close this because it is not Marp CLI's issue.

**Comment by jhconning** [comment]
Thank you!  You were correct, adding the `--html` option fixed the problem.
