### ISSUE TITLE
Html tags at the end of the file break css theme loading and `--html false` doesn't behave the same as unspecified html setting

### ISSUE THREAD

**Issue by pavelzw** [marp-team/marp-cli#511]
### Version of Marp Tool

@marp-team/marp-cli v2.4.0 (w/ @marp-team/marp-core v3.5.0)

### Operating System

macOS

### Environment

- OS version: macOS 13.2.1
- Node.js version 19.7.0

### How to reproduce

test.md
```md
---
marp: true
---

# Test **title**

<div></div>
```
(here no trailing whitespace!)

test.css
```css
/* @theme test */
@charset "UTF-8";

section {
  background-color: white;
  font-size: 35px;
  color: red;
}

```

Compare the output of these three commands:

```shell
marp --theme test.css -o test.pdf test.md
marp --theme test.css -o test.pdf test.md --html true
marp --theme test.css -o test.pdf test.md --html false
```

### Expected behavior

The theme should be loaded everywhere and the output of the first and third command should be the same. Additionally, it should look the same with and without a new line at the end in `test.md`

```shell
marp --theme test.css -o test.pdf test.md
```
Expected:
![image](https://user-images.githubusercontent.com/29506042/224752211-f4143ff7-b0d3-4de8-aa87-c057e9ab1c3d.png)

```shell
marp --theme test.css -o test.pdf test.md --html true
```
Expected:
![image](https://user-images.githubusercontent.com/29506042/224752496-1658e84f-94bd-4311-a0f1-784a8ae7e241.png)

```shell
marp --theme test.css -o test.pdf test.md --html false
```
Expected:
![image](https://user-images.githubusercontent.com/29506042/224752785-fbeb0cc5-f2a5-4f65-b50b-51d8eecaf73a.png)

### Actual behavior

The first and third commands differ in output (see screenshots below) and the theme loading breaks if no newline is present at the end of `test.md` if `--html false` isn't set explicitly.

```shell
marp --theme test.css -o test.pdf test.md
```
Actual: 
![image](https://user-images.githubusercontent.com/29506042/224753263-447a6804-b1ec-4a62-b5fe-8cb3b10db961.png)

```shell
marp --theme test.css -o test.pdf test.md --html true
```
Actual:
![image](https://user-images.githubusercontent.com/29506042/224753143-e0e3f49f-14b4-4541-8c6a-e1da15ac4fcc.png)

```shell
marp --theme test.css -o test.pdf test.md --html false
```
Actual:
![image](https://user-images.githubusercontent.com/29506042/224753022-cf70a218-58e2-4552-b8bf-696fa5fda799.png)

### Additional information

This issue contains two bugs, but the html flag bug cannot be replicated without the other one as an example.

The div bug can also be replicated using other block elements such as `<main></main>`, `<header></header>` etc., but not with inline elements such as `<span></span>`. It does however break when using the "short hand" notation `<span />`.

**Comment by yhatt** [comment]
Good catch! I'm sure that bug has been around in Marp CLI for a long time.

I'm going to fix that by using an internal Marpit plugin, instead of the content injection to Markdown (described in following).

### Details

The internal operation of the `--theme` option in Marp CLI is [generating a unique name for the theme CSS automatically](https://github.com/marp-team/marp-cli/blob/d31219521c9adba7366121f1deaf05394f14c2af/src/theme.ts#L39-L43) and [applying it by inserting an HTML comment `<!-- theme: (generated name) -->` at the end of the Markdown](https://github.com/marp-team/marp-cli/blob/d31219521c9adba7366121f1deaf05394f14c2af/src/converter.ts#L157-L165).

```markdown
---
marp: true
---

# Test **title**

<div></div>
<!-- theme: 33mkms86s8i6jm51 -->
```

In this example, `33mkms86s8i6jm51` is a unique value generated by Marp CLI. If `--html` option was not enabled, the overloaded global directive works as intended.

Now, an important thing is that Marp's directive definitions using HTML comments are [recognized only for HTML blocks where the beginning or entire of block is a comment](https://github.com/marp-team/marpit/blob/118e994b72244a48e6d4cf1922e9bb319fb81924/src/markdown/comment.js#L50-L52). In the above example, `theme` directive won't be parsed as a directive.

By enabling HTML through `--html` option, I guess an internally injected `<!-- theme: 33mkms86s8i6jm51 -->` might be incorporated as part of the HTML tag block at the last of Markdown.
