### ISSUE TITLE
Keyboard shortcuts for moving quickly inside the presentation

### ISSUE THREAD

**Issue by pprw** [marp-team/marp-cli#564]
For long presentation with many many slides, it could be laborious to go to a peculiar point.

Implementing basic keyboard shortcut such as
- go to the last slide (suggestion: ctrl+rightarrow)
- go to the first slide (suggestion: ctrl+leftarrow)
- go the the new title of h1 level (suggestion: (h)

would fixes that.

This is a remark in the same spirit than https://github.com/marp-team/marp-cli/issues/206.

P-S: today, up, down and right,left arrow are used for the same thing (moving of one slide). up and down arrow could be used to moving of 10 slides)

**Comment by yhatt** [comment]
> - go to the last slide (suggestion: ctrl+rightarrow)
> - go to the first slide (suggestion: ctrl+leftarrow)

It's worth noting that Marp CLI already supports navigation to the first and last slides using the <kbd>Home</kbd> and <kbd>End</kbd> keys.

> - go the the new title of h1 level (suggestion: (h)

We are reluctant to make this suggestion. It depends on the document whether the Markdown slides comply with the heading level.

> up and down arrow could be used to moving of 10 slides

Marp CLI is not adopting to make different actions for up and down keys, because it will break compatibility with common presentation tools such as PowerPoint. That may surprise users who are familiar with them.

If necessary, you can make your own HTML presentation system with your ideal keyboard shortcuts by integrating Marp through [Marp Core](https://github.com/marp-team/marp-core) :)
