### ISSUE TITLE
HTML not interpreted with CLI

### ISSUE THREAD

**Issue by cansik** [marp-team/marp-cli#57]
I use HTML tags in my presentation to include an image and show it on the right side. Everything works fine while using the marp editor, but when I would like to build it with the CLI version, the HTML tags are not evaluated. Not in `server` or `preview` mode and not with `allow-local-files` and not with `pdf` or `html` output.

The pdf gets render correctly only when using the `Export to pdf` method in the marp editor itself.

Would be great if you could give me a hint. Here are some screenshots of the problem:

![image](https://user-images.githubusercontent.com/5220162/50726577-972cfb80-110f-11e9-90ee-7952c28f5fd6.png)
*Marp editor with html tag*

```bash
marp --pdf --allow-local-files Abstrakteklassen.md
```
*Marp CLI build command*

![image](https://user-images.githubusercontent.com/5220162/50726596-e7a45900-110f-11e9-80f8-30236c0395b8.png)
*Rendered PDF*

**Comment by yhatt** [comment]
Try `--html` option.

```
marp --html --pdf --allow-local-files Abstrakteklassen.md
```

Marp CLI would escape HTML by default because of several security reason. Refer to: [CVE-2017-2239](https://nvd.nist.gov/vuln/detail/CVE-2017-2239), marp-team/marp-core#9, marp-team/marp-core#26, yhatt/marp#259

**Comment by cansik** [comment]
Ok nice, that worked...but the rendered output is not the same as with Marp. The `align="right"` is not interpreted.

```html
## Abstrakte Klassen - Store

<img src="diagrams/store_oop.svg" width="600" align="right">

- Alle Klassen können **instanziert** werden
- Die Kindklassen **müssen** keine Funktion überschreiben

Article a1 = new Article(23, "Test1");
Article a2 = new Book(12, "Test2");
```

Gets rendered like this:

![image](https://user-images.githubusercontent.com/5220162/50741690-e737bb00-1200-11e9-9bee-207521237789.png)

**Comment by yhatt** [comment]
In the complete re-written tools released by marp-team, included Marp CLI, you should not expect the exactly same result with [yhatt/marp](https://github.com/yhatt/marp). In this case, yhatt/marp's older Chromium has wrong rendering.

[According to W3C](https://www.w3.org/TR/css-flexbox-1/), the floating element in flexbox is ignored. Marp slide has consisted of flex container, and the floating by `align=right` should be ignored.

ref: https://stackoverflow.com/a/39194800

Instead of `align=right`, you can use [split background](https://marpit.marp.app/image-syntax?id=split-backgrounds) by `![bg right](bg.jpg)`

```markdown
![bg right w:600](diagrams/store_oop.svg)
```

**Comment by cansik** [comment]
Ok, I got it now...I was a bit confused with the difference between marp-cli, marpit, marpcore, marp, and yhatt/marp.

Just that I am not missing anything, there is currently no marp editor for the new version, which works as yhatt/marp?

**Comment by yhatt** [comment]
*You are right: Currently marp-team have not provide an editor.* I have not the time to develop a editor because currently I focus to the [minimum viable product](https://en.wikipedia.org/wiki/Minimum_viable_product), that is the conversion from Markdown to slide deck.

At the moment, the most similar usage is the combination with Marp CLI's preview mode (`marp -p`) and your favorite editor, Vim, Emacs, Atom, VSCode, etc...

In future, [marp-team/marp-web](https://github.com/marp-team/marp-web) (*In development*: https://web.marp.app/) would become a new editor. Sometime I'm going to create blog and explain about the whole of our project clearly. (marp-team/marp#11) Please excuse my lack of explanation!

**Comment by cansik** [comment]
Thanks for the clarification (: and great piece of software! 👍
