### ISSUE TITLE
App crashes after double-click to start

### ISSUE THREAD

**Issue by Ares960826** [marp-team/marp-cli#585]
I'm experiencing a crash when starting the app. The app suddenly closes without any error message.

+ Device Information: Window 10
+ App Version: 3.4.0

**Comment by yhatt** [comment]
Don't open with double click. Thats result is natural because Marp CLI is not GUI/frontend tool (as name suggests). Marp CLI is designed for command line interface (CLI) so you should run it from the command prompt (cmd.exe) or PowerShell.

```
marp.exe your-markdown.md
```

If double-clicked the executable file, CLI will exit immidiately because that has not passed Markdown file(s) to convert.

Also refer to same misunderstandings: https://github.com/marp-team/marp-cli/issues/126#issuecomment-511004674, https://github.com/marp-team/marp-cli/issues/505#issuecomment-1438330893
