### ISSUE TITLE
The `punycode` module is deprecated (when installed via Homebrew).

### ISSUE THREAD

**Issue by MichaelCharles** [marp-team/marp-cli#596]
### Version of Marp Tool

@marp-team/marp-cli v3.4.0 (w/ @marp-team/marp-core v3.9.0)

### Operating System

macOS

### Environment

- OS version: macOS Sequoia 15
- Node.js version (Marpit / Marp Core/ Marp CLI): Reproduced with both v18.20.4 and v20.17.0 installed globally. I think that since this was installed with Homebrew, the globally installed Node version is unrelated.
- VS Code version (Marp for VS Code): Not relevant.
- Homebrow Version: 4.3.24

### How to reproduce

Install `marp-cli` via Homebrew: `brew install marp-cli`

Execute any command,

```
➜ marp --html presen.md
(node:37034) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:37034) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
[  INFO ] Converting 1 markdown...
[  INFO ] presen.md => presen.html
```

### Expected behavior

I expect that deprecation warnings will not show. 

### Actual behavior

Deprecation warnings show. 

### Additional information

This seems to have been already resolved [here](https://github.com/marp-team/marp-cli/issues/574), and if I install `marp-cli` via `npm install -g @marp-team/marp-cli` rather than via `brew install marp-cli`, even though the versions are identical (`@marp-team/marp-cli v3.4.0 (w/ @marp-team/marp-core v3.9.0)`) I do not get the deprecation warning. The deprecation warning only appears when installed via Homebrew.

**Comment by yhatt** [comment]
> I think that since this was installed with Homebrew, the globally installed Node version is unrelated.

It is actually related because [Homebrew's Marp formula is depending on node formula](https://github.com/Homebrew/homebrew-core/blob/5c4268486784461508411ab78106c72a0ed357bb/Formula/m/marp-cli.rb#L20C3-L20C13). Homebrew will install [the latest version v22](https://formulae.brew.sh/formula/node) instead of [recommended LTS Node.js version v20](https://nodejs.org/). So if the result of `node -v` is `v22.x.x`, deprecation warnings may be shown.

That will be fixed by #591, that is going to include in next release  Marp CLI v4 ([CHANGELOG](https://github.com/marp-team/marp-cli/blob/c727e9cf73faa32cbb926bb281de5dfd0dc86b33/CHANGELOG.md?plain=1#L28)). Basically, you don't need to care their deprecations for now, but try to install Node.js LTS if you concerned.
