### ISSUE TITLE
[Feature Request] image location

### ISSUE THREAD

**Issue by inktvis75** [marp-team/marp-cli#613]
Is it possible / can you add a parameter to point to the location (in my setup, it differs from the location of the markdown file)

**Comment by yhatt** [comment]
It's currently available, but provides as an _**[CLI API](https://github.com/marp-team/marp-cli#api-experimental) option only**_ because we have recognized as that feature may confuse users if provided as a CLI option.



```javascript
import { marpCli } from '@marp-team/marp-cli'

await marpCli(['example.md'], {
  baseUrl: 'file:///path/to/resources/example.md'
})
```

In this example, every resource in Markdown will be resolved with the base URL `file:///path/to/resources/example.md`. So the relative path such as `./image.png` will always be resolved as `file:///path/to/resources/image.png` as like as placed Markdown at `file:///path/to/resources/example.md`. See [the reference of the `<base>` element](https://developer.mozilla.org/docs/Web/HTML/Element/base) about the base URL.

For example, we are using this option in Marp for VS Code, to provide the export command through the proxy server that is connecting to VS Code workspace. (https://github.com/marp-team/marp-vscode/pull/367)
