### ISSUE TITLE
Is the marp-cli's Markdown syntax the same as the old Marp?

### ISSUE THREAD

**Issue by kakyoism** [marp-team/marp-cli#85]
I still enjoy the old desktop version and wonder if my old slides can migrate to marp-cli well.

Thanks!

**Comment by yhatt** [comment]
There are the pointed concerns in [the all of Marp Next tools](https://github.com/marp-team/marp) not only CLI. We are planning to explain about migration in our blog, and [there is a draft at here](https://github.com/marp-team/marp/blob/2c61f6e7c21c639830b5a0565561c6310bc54467/website/blog/2019-04-02-the-story-of-marp-next/the-story-of-marp-next.md#your-slide-deck). 

Because still remaining a lot of tasks for the other Marp Next tools, I can't get around to opening blog yet. We welcome to contribution by community to help migration the old Marp slides.

**Comment by evanchan92** [comment]
I've found the mixture of HTML and MD wouldn't work out in the new Marp-Cli.
```
<center> ![](www.balabala.com/sdf.jpg)
```
Can work on the old desktop version, but not the new one.

It will definitely help for amateurs like me for allowing us to use simple HTML language rather than the whole set.

**Comment by yhatt** [comment]
Marp Next would escape non-whitelisted HTML by default. It's important for security because the old application had offered a target of vulnerability by allowed any HTML. (Refer to https://github.com/marp-team/marp-cli/issues/57#issuecomment-451723617)

Just use `--html` option to allow any HTML. It might have to explain too.
